feat(avatar): add support for three characters
innovaccer/design-system pull request #1009
Opened 2021-12-21 20:20 UTC by SaniyaGupta

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2021-12-23 09:08 UTC, mukuljainx requested changes
Apart from mentioned changes can you please also took care of these too?

https://github.com/innovaccer/design-system/blob/a27fffa971cfabb999dfe0151ed242f7b9858cef/core/components/atoms/avatarGroup/AvatarGroup.tsx#L177

Can you change this function call to React component ?
And instead of renderPopper to `PopoverBody`, I wanted it for all popper keyword but sadly that has been exposed in API too!


https://github.com/innovaccer/design-system/blob/a27fffa971cfabb999dfe0151ed242f7b9858cef/core/components/atoms/avatarGroup/AvatarGroup.tsx#L167

Same goes for this functional call, `Avatars` or `AvatarList` should do it.


https://github.com/innovaccer/design-system/blob/a27fffa971cfabb999dfe0151ed242f7b9858cef/core/components/atoms/avatarGroup/AvatarGroup.tsx#L72

This one too.

2021-12-23 09:08 UTC, mukuljainx commented on core/components/atoms/avatarGroup/AvatarGroup.tsx
> +                className={ind < extraAvatarsList.length - 1 ? 'mb-5' : ''}
can we use `classNames` package here too?

2021-12-23 09:08 UTC, mukuljainx commented on core/components/atoms/avatarGroup/AvatarGroup.tsx
> +  const extraAvatars = list.length > max ? (list.length - max > 99 ? 99 : list.length - max) : 0;
please change the variable name to `turncatedAvatarCoun` or more suitable
 
and can we use `Math.max` for second comparison? seems more readable.
```tsx
const hiddenAvatarCount = list.length - max > 0 ? Math.max(list.length - max, 99): 0;
```

2021-12-23 09:08 UTC, mukuljainx commented on core/components/atoms/avatarGroup/AvatarGroup.tsx
> +import ExtraAvatars from './ExtraAvatars';
Can we rename it to `AvatarCount`?

2021-12-23 12:05 UTC, SaniyaGupta commented on core/components/atoms/avatarGroup/AvatarGroup.tsx
> +  const extraAvatars = list.length > max ? (list.length - max > 99 ? 99 : list.length - max) : 0;
Math.max will not work here, because if count is less than 99 then we have to show it, so Math.min will work here

2021-12-27 07:46 UTC, mukuljainx approved these changes

2021-12-28 06:18 UTC, veekays approved these changes

2021-12-28 06:18 UTC, merged