fix(calendar): update states for calendar component
innovaccer/design-system pull request #1602
Opened 2022-12-06 07:38 UTC by Rashi-Gupta-2000

### What does this implement/fix? Explain your changes.

Had to update states for the date range picker and hence after confirmation all states for the calendar were updated too.

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2022-12-08 13:14 UTC, satyamyadav requested changes

2022-12-08 13:14 UTC, satyamyadav commented on core/components/organisms/calendar/Calendar.tsx
> +            if (active) return 'white';
Please use multiline blocks.

2022-12-08 13:14 UTC, satyamyadav commented on core/components/organisms/calendar/Calendar.tsx
> +            else return 'inverse';
If possible please covert to switch case.

2022-12-08 13:14 UTC, satyamyadav commented on core/components/organisms/calendar/Calendar.tsx
> +            else return 'inverse';
or use classNames function to evaluate.

2022-12-08 13:14 UTC, satyamyadav commented on core/components/organisms/calendar/Calendar.tsx
> +
Please use className function to evaluate the color.

2022-12-08 13:14 UTC, satyamyadav commented on core/components/organisms/calendar/Calendar.tsx
>              return (
Please use className function to evaluate color.

2022-12-08 13:14 UTC, satyamyadav commented on css/src/components/calendar.css
> +
Please follow BEM conventions for CSS.

2022-12-12 08:42 UTC, anuradha9712 commented on css/src/components/calendar.css
> +
Please follow BEM conventions for CSS.

2022-12-12 08:45 UTC, anuradha9712 commented on core/components/organisms/calendar/__tests__/Calendar.test.tsx
> +
Please write valid test cases for Calendar component instead of writing redundant test cases for Text component

2022-12-12 08:47 UTC, anuradha9712 commented on core/components/organisms/calendar/__tests__/Calendar.test.tsx
> +
Please remove this redundant test case

2022-12-12 08:47 UTC, anuradha9712 commented on core/components/organisms/calendar/__tests__/Calendar.test.tsx
> +
Please remove this redundant test case

2022-12-12 08:47 UTC, anuradha9712 commented on core/components/organisms/calendar/__tests__/Calendar.test.tsx
> +});
Please remove this redundant test case

2023-01-23 10:47 UTC, varnikajain15 requested changes

2023-01-23 10:47 UTC, varnikajain15 commented on css/src/components/calendar.css
> +  font-weight: var(--font-weight-bold);
There is no need to define font-weight again. It will pick from the parent class i.e. **Calendar-value--active**.

2023-01-23 10:47 UTC, varnikajain15 commented on css/src/components/calendar.css
> +  background: var(--primary-lighter);
We can define a new class to handle this as we avoid using specificity CSS selectors. Please check once.

2023-02-14 05:22 UTC, closed without merging