fix(dropzone): formet label updated as per the accept props in stories
innovaccer/design-system pull request #1620
Opened 2022-12-19 06:45 UTC by samyak3009

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2022-12-19 07:36 UTC, varnikajain15 approved these changes, later dismissed

2022-12-19 08:34 UTC, anuradha9712 commented
Please fix all the stories and remove all discrepancies between `accept` prop & format that are actually acceptable

2022-12-19 13:13 UTC, anuradha9712 commented
Please pass correct `minSize` & `maxSize` according to the **sizeLabel** defined in the story

2022-12-20 12:41 UTC, veekays requested changes
please make sure to have 1 commit instead of 2.

2022-12-20 14:05 UTC, veekays approved these changes

2022-12-20 14:06 UTC, merged