fix(dropdown): selected value can be select again in menu
innovaccer/design-system pull request #1630
Opened 2022-12-22 07:38 UTC by samyak3009

### What does this implement/fix? Explain your changes.
we can select the option again which is already selected and callback function will also called everytime we select the already selected value.
...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2022-12-22 08:16 UTC, anuradha9712 requested changes
Please add a test case for both the scenarios when `menu={true}` & `menu={false}`

2022-12-28 06:22 UTC, satyamyadav commented
@samyak3009  Can you please update/add the test case.

2023-01-10 13:26 UTC, anuradha9712 requested changes
Please add a valid test case for Controlled dropdown as well and check for both `onChange` & `onUpdate` callback functions to be triggered correctly.

2023-01-11 10:51 UTC, anuradha9712 requested changes
Please change the commit message

2023-01-11 10:52 UTC, anuradha9712 commented on core/components/atoms/dropdown/__tests__/Dropdown.test.tsx
> +    const { getByTestId, getAllByTestId } = render(<Dropdown options={dropdownOptions} onChange={FunctionValue} />);
Please add a new line after `it` block

2023-01-11 13:49 UTC, anuradha9712 approved these changes

2023-01-11 13:49 UTC, merged