fix(collapsible): replace style tag with classname in stories
innovaccer/design-system pull request #1639
Opened 2022-12-27 07:39 UTC by Rashi-Gupta-2000

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2022-12-27 08:59 UTC, aman2000verma requested changes

2022-12-27 08:59 UTC, aman2000verma commented on core/components/atoms/collapsible/__stories__/index.story.jsx
> +    <div className="d-flex">
Please use `vh-100` class instead of `d-flex`.
You can refer [here](https://mds.innovaccer.com/?path=/story/others-styles-sizing--sizing)

2022-12-27 10:11 UTC, aman2000verma approved these changes, later dismissed

2022-12-28 05:36 UTC, satyamyadav requested changes

2022-12-28 05:36 UTC, satyamyadav commented on core/components/atoms/collapsible/__stories__/index.story.jsx
> +    <div className="d-flex">
Please verify and remove the wrapper div as it does not seem to be affecting anything.

2022-12-28 09:28 UTC, satyamyadav approved these changes

2022-12-28 09:35 UTC, merged