fix(textarea): replace style tag with classname in stories
innovaccer/design-system pull request #1642
Opened 2022-12-27 10:22 UTC by Rashi-Gupta-2000

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2022-12-28 06:02 UTC, satyamyadav requested changes

2022-12-28 06:02 UTC, satyamyadav commented on core/components/atoms/textarea/__stories__/index.story.jsx
> +    <div className="Textarea-wrapper">
Please use `className="w-25"` instead.

2022-12-28 06:02 UTC, satyamyadav commented on core/components/atoms/textarea/__stories__/variants/Disable.story.jsx
> +        <div className="mr-9 mb-5 d-flex flex-column align-items-center Textarea-wrapper" key={ind}>
Please refactor it in a cleaner manner. We can reduce the extra html and classnames by using `Row`, `Column` and `Label` like this example https://codesandbox.io/s/young-bush-r9jf2c?file=/index.js

2023-01-03 10:09 UTC, anuradha9712 approved these changes

2023-01-04 05:50 UTC, anuradha9712 approved these changes

2023-01-06 13:53 UTC, satyamyadav approved these changes

2023-01-09 08:50 UTC, merged