fix(icon): replace style tag with classname in stories
innovaccer/design-system pull request #1655
Opened 2022-12-29 19:35 UTC by Rashi-Gupta-2000

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2023-01-03 05:50 UTC, anuradha9712 requested changes
Instead of writing separate style please move the `className='bg-dark'` to Icon component

2023-01-03 05:51 UTC, anuradha9712 commented on core/components/atoms/icon/__stories__/variants/style.css
> +    width: 50px;
Please remove this style

2023-01-03 12:25 UTC, anuradha9712 approved these changes, later dismissed

2023-01-06 13:48 UTC, satyamyadav approved these changes

2023-01-09 08:25 UTC, merged