fix(chipInput): replace style tag with classname in stories
innovaccer/design-system pull request #1659
Opened 2022-12-29 20:53 UTC by Rashi-Gupta-2000

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2023-01-03 06:18 UTC, anuradha9712 requested changes
Please use `Col--4` className instead of using fixed width

2023-01-03 06:19 UTC, anuradha9712 commented on core/components/molecules/chipInput/__stories__/style.css
> +    width: 320px;
Please remove this class

2023-01-04 05:42 UTC, anuradha9712 approved these changes, later dismissed

2023-01-06 11:33 UTC, satyamyadav requested changes

2023-01-06 11:33 UTC, satyamyadav commented on core/components/molecules/chipInput/__stories__/ChipsWrapped.story.jsx
> +    <div className="Col--4">
Please use `<Column size={4}>` or width-based classes, Column should not be used without Row as a parent, and classes of columns should not be used in react as this is a component class and not a utility.

2023-01-09 05:54 UTC, anuradha9712 approved these changes

2023-01-09 12:59 UTC, satyamyadav approved these changes

2023-01-09 12:59 UTC, merged