fix(pageHeader): replace style tag with classname in stories
innovaccer/design-system pull request #1665
Opened 2022-12-30 19:44 UTC by Rashi-Gupta-2000

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2023-01-03 06:47 UTC, anuradha9712 commented on core/components/organisms/pageHeader/__stories__/withFilter.story.jsx
> +    <div className="py-6 bg-secondary-lightest Pageheader-wrapper">
Please remove the `Pageheader-wrapper` class. This class does not make much difference or can we please use `Col--11` class

2023-01-03 06:49 UTC, anuradha9712 commented on core/components/organisms/pageHeader/__stories__/withFilterL1.story.jsx
> +}
Please remove this custom style. This does not seems to make any difference.

2023-01-03 06:52 UTC, anuradha9712 commented on core/components/organisms/pageHeader/__stories__/withNavigation.story.jsx
> +}
Instead of writing fixed width, please use `w-100` or `Col--11` class

2023-01-03 06:54 UTC, anuradha9712 commented on core/components/organisms/pageHeader/__stories__/withNavigationL1.story.jsx
> +}
Please remove this fixed width

2023-01-04 07:44 UTC, anuradha9712 submitted a review, later dismissed

2023-01-09 11:35 UTC, anuradha9712 requested changes
Please check the same stories on docs site as well

2023-01-09 12:24 UTC, Rashi-Gupta-2000 commented
> Please check the same stories on docs site as well

Then custom css will have to applied making a seprate .css file

2023-01-11 11:20 UTC, closed without merging