chore(actions): add test job for docs site after deployment
innovaccer/design-system pull request #1682
Opened 2023-01-06 10:24 UTC by varnikajain15

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2023-01-06 10:39 UTC, aman2000verma submitted a review, later dismissed

2023-01-06 10:41 UTC, anuradha9712 submitted a review, later dismissed

2023-01-09 10:21 UTC, aman2000verma submitted a review, later dismissed

2023-01-09 10:22 UTC, anuradha9712 approved these changes

2023-01-09 12:09 UTC, anuradha9712 requested changes
Please check the host url for which this test will run. Currently it will check the site hosted on `localhost:9000`

2023-03-30 11:51 UTC, closed without merging