fix(collapsible): update width for collapsible component
innovaccer/design-system pull request #1686
Opened 2023-01-10 08:24 UTC by Rashi-Gupta-2000

### What does this implement/fix? Explain your changes.
Changed the width for the Vertical Nav scrollbar fix.
...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2023-01-10 11:57 UTC, varnikajain15 requested changes

2023-01-10 11:57 UTC, varnikajain15 commented on css/src/components/collapsible.css
> +  width: 48px;
Please, use design system token for this.

2023-01-12 07:17 UTC, varnikajain15 submitted a review, later dismissed

2023-01-13 08:06 UTC, varnikajain15 requested changes

2023-01-13 08:06 UTC, varnikajain15 commented on core/components/atoms/collapsible/Collapsible.tsx
> +    ['Collapsible-body--hoverable']: !expanded && hoverable,
Can we replace the class name with our design token **overflow-hidden**? Please check.

2023-01-16 06:45 UTC, varnikajain15 submitted a review, later dismissed

2023-01-19 08:13 UTC, anuradha9712 approved these changes

2023-01-19 08:21 UTC, merged