fix(verticalNav): fix overlap of scrollbar on verticalNav
innovaccer/design-system pull request #1687
Opened 2023-01-10 08:28 UTC by Rashi-Gupta-2000

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2023-01-10 10:50 UTC, varnikajain15 approved these changes, later dismissed

2023-01-10 13:42 UTC, anuradha9712 requested changes
Vertical nav scroll bar issue still persists. Please check all the stories

2023-01-10 13:45 UTC, Rashi-Gupta-2000 commented
> Vertical nav scroll bar issue still persists. Please check all the stories

We need to combine this with the Collapsible PR to see the final output.

2023-01-12 07:18 UTC, varnikajain15 approved these changes, later dismissed

2023-01-19 08:22 UTC, anuradha9712 approved these changes

2023-01-19 08:30 UTC, merged