feat(tabs): add states of custom icon button in tabs
innovaccer/design-system pull request #1692
Opened 2023-01-10 12:47 UTC by Rashi-Gupta-2000

### What does this implement/fix? Explain your changes.

add states of custom icon button in tabs

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2023-01-12 12:38 UTC, varnikajain15 commented
![Screenshot from 2023-01-12 18-06-59](https://user-images.githubusercontent.com/55780559/212068419-e9f48d9a-b248-4262-85a6-aa049d63754b.png)
This is not looking as per design. Please check.

2023-01-12 12:43 UTC, Rashi-Gupta-2000 commented
> ![Screenshot from 2023-01-12 18-06-59](https://user-images.githubusercontent.com/55780559/212068419-e9f48d9a-b248-4262-85a6-aa049d63754b.png) This is not looking as per design. Please check.

The states are exactly as in design please be specific about the issue, also the padding and spacing are not to fixed in this PR.

2023-01-16 06:46 UTC, varnikajain15 submitted a review, later dismissed

2023-01-16 08:15 UTC, anuradha9712 requested changes
Please add a test cases for your changes

2023-01-18 10:17 UTC, anuradha9712 approved these changes

2023-01-18 10:18 UTC, merged