fix(horizontalNav): update active state of selected nav item
innovaccer/design-system pull request #1693
Opened 2023-01-10 12:59 UTC by varnikajain15

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2023-01-12 06:06 UTC, Rashi-Gupta-2000 commented on core/components/organisms/horizontalNav/HorizontalNav.tsx
> +        <Icon className="mr-3 HorizontalNav-animate" name={menu.icon} data-test="DesignSystem-HorizontalNav--Icon" />
Please do not replace appearance with CSS but just override the need CSS.

2023-01-12 06:06 UTC, Rashi-Gupta-2000 commented on css/src/components/horizontalNav.css
> +  color: var(--inverse-lightest);
Please keep this in the JS file so that there is no redundant work.

2023-01-12 07:10 UTC, Rashi-Gupta-2000 submitted a review, later dismissed

2023-01-16 08:04 UTC, anuradha9712 commented on css/src/components/horizontalNav.css
> +  color: var(--inverse);
We are using the same colours for MenuText as well. Please create a common function to get colours for both MenuWrapper and MenuText and reuse it.

2023-01-16 08:22 UTC, anuradha9712 commented on core/components/organisms/horizontalNav/HorizontalNav.tsx
> +    const color = getTextColor(isActive, menu.disabled);
Please change the function name and variable name

2023-01-16 08:25 UTC, anuradha9712 requested changes
Please add a test cases to check the correct classes used based on various conditions

2023-01-16 12:44 UTC, anuradha9712 approved these changes

2023-01-16 12:45 UTC, merged