fix(dateRangePicker): same start date and end date selection
innovaccer/design-system pull request #1701
Opened 2023-01-17 07:30 UTC by Rashi-Gupta-2000

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2023-01-17 08:43 UTC, varnikajain15 submitted a review, later dismissed

2023-01-18 07:53 UTC, anuradha9712 requested changes
Please write a test cases

2023-01-18 13:30 UTC, anuradha9712 requested changes
Please write a test case to check if `onRangeChange` callback function is called on selection of same start and end date

2023-01-18 13:33 UTC, anuradha9712 requested changes
Add a test case to check if user is able to select same start/end date from dateRangePicker and values are updated correctly in singleInput.

2023-01-20 12:05 UTC, anuradha9712 approved these changes

2023-01-20 12:05 UTC, merged