feat(tooltip): added prop to conditionally render tooltip
innovaccer/design-system pull request #2026
Opened 2023-11-18 08:21 UTC by tenx96

### What does this implement or fix? Explain your changes.
Added a `showTooltip` prop to the Tooltip component to conditionally render tooltip text

One of the most common uses of tooltip is to show a tooltip message when an action is disabled based on some flags

Say you have a button that is disabled or enabled by using a permission flag
And we need to show a tooltip with a reason when the button is disabled.
The current Tooltip component doesn't have any support for conditional rendering and we are forced to write a component like below

``` javascript
  const disabled = true;
  const disableReason = "User does not have permission to update";
  
  const completeBtn = (
    <Button disabled={disabled} aria-label="Complete" type="button">
      Complete
    </Button>
  );

  return (
    <div>
      {disabled ? (
        <Tooltip tooltip={disableReason}>{completeBtn}</Tooltip>
      ) : (
        { completeBtn }
      )}
    </div>
```
With this prop `showTooltip` the code above can be simplified into
``` javascript
<div>
  <Tooltip showTooltip={disabled} tooltip={disableReason}>
    <Button disabled={disabled} aria-label="Complete" type="button">
      Complete
    </Button>
  </Tooltip>
</div>
```

This is a very common usage pattern, and this simple prop can improve how the tooltip is used.
...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2023-11-27 10:56 UTC, anuradha9712 commented on core/components/molecules/tooltip/__stories__/Conditional.story.jsx
> +export const conditional = () => {
Please change the function name

2023-11-27 10:58 UTC, anuradha9712 requested changes
Please change the commit message

2023-11-27 10:59 UTC, anuradha9712 requested changes
Please create a pull request to `develop` branch instead of `master` branch directly

2023-11-29 18:41 UTC, tenx96 commented on core/components/molecules/tooltip/__stories__/Conditional.story.jsx
> +export const conditional = () => {
Updated.
Please check

2023-11-29 18:48 UTC, tenx96 commented
@anuradha9712 
I've updated the story using `customCode` and added a switch to toggle 'showTooltip'.

2023-11-30 13:45 UTC, anuradha9712 commented
Please squash your commit to a single commit instead of 2.

2023-11-30 13:46 UTC, anuradha9712 commented
Please avoid using "add**ed**" from the commit message. You can simply use feat(tooltip): add support for conditional rendering in tooltip" message

2023-11-30 13:58 UTC, anuradha9712 commented on core/components/molecules/tooltip/__stories__/ShowTooltip.story.jsx
> +    </div>
Can we please avoid using multiple div and simply try to align it vertically to make the code more readable.

```
<div>
        <div className="mb-6 d-flex">
          <Label className="mr-4">Show Tooltip</Label>
          <Switch
            value={showTooltip}
            aria-label="Toggle tooltip"
            size="tiny"
            onChange={(_, selected) => setShowTooltip(selected)}
          />
        </div>
  
        <Tooltip showTooltip={showTooltip} tooltip="An awesome tooltip">
          <Button>Conditional Tooltip</Button>
        </Tooltip>
      </div>
```

2023-12-01 17:24 UTC, mairing-hojai commented on core/components/molecules/tooltip/__stories__/ShowTooltip.story.jsx
> +    </div>
Updated.
Thanks for the suggestion

2023-12-05 16:17 UTC, mairing-hojai commented
@anuradha9712 Please see if there are any more issues.
Thank you

2023-12-06 07:06 UTC, anuradha9712 approved these changes

2023-12-06 07:06 UTC, merged