fix: add compatible support for metric input and textarea for firefox
innovaccer/design-system pull request #2030
Opened 2023-11-25 19:28 UTC by youngheart12

### What does this implement/fix? Explain your changes.
This fix the issue of having double increment and decrement sign in firefox and resize by default not available in textarea
...

### Does this close any currently open issues?
yes 
...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2023-11-27 11:02 UTC, anuradha9712 requested changes
Please change the commit message

2023-11-27 11:02 UTC, anuradha9712 requested changes
Please do not commit the `package-lock.json` file

2023-11-27 11:03 UTC, anuradha9712 requested changes
Please create a pull request to `develop` branch instead of `master` branch directly.

2023-11-27 20:32 UTC, youngheart12 commented
@anuradha9712 Changed as the way you suggested.

2023-11-27 20:35 UTC, youngheart12 commented
<img width="1440" alt="Screenshot 2023-11-28 at 2 04 16 AM" src="https://github.com/innovaccer/design-system/assets/33593316/35f1238f-f449-4a65-97a7-9cfc00a65235">

<img width="1440" alt="Screenshot 2023-11-28 at 2 04 23 AM" src="https://github.com/innovaccer/design-system/assets/33593316/53f5c5f5-7a23-4c5b-a3a1-0c939ce2cf88">


Screenshot from the firebox browser.

2023-11-30 14:02 UTC, anuradha9712 requested changes
Please create a separate PR for each component related changes

2024-01-30 09:32 UTC, satyamyadav commented
@youngheart12  Closing it as the changes are already done in two other PRs. #2038 #2037

2024-01-30 09:32 UTC, closed without merging