fix: add compatibility for metric input in Firefox
innovaccer/design-system pull request #2037
Opened 2023-12-13 14:09 UTC by youngheart12

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2023-12-13 14:20 UTC, youngheart12 commented
<img width="1440" alt="Screenshot 2023-12-13 at 7 50 30 PM" src="https://github.com/innovaccer/design-system/assets/33593316/3f296867-faee-41f0-b8dc-0b32c0eb8af4">

2024-01-30 09:47 UTC, satyamyadav requested changes

2024-01-30 09:47 UTC, satyamyadav commented on css/src/components/metricInput.css
> +  -webkit-appearance: textfield;
Please add  `appearance: textfield` in stead, post css will take care of browser vendor style prefix. You can try it here https://autoprefixer.github.io/ 
Please check if `appearance: none` works then use it in stead.

2024-08-16 11:49 UTC, innosatyam commented
Closing due to inactivity.

2024-08-16 11:49 UTC, closed without merging