feat(chat): add new AI Chat component
innovaccer/design-system pull request #2210
Opened 2024-05-30 14:41 UTC by anuradha9712

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2024-06-06 14:39 UTC, samyak3009 requested changes

2024-06-06 14:39 UTC, samyak3009 commented on core/ai-components/AIResponse/ChatBox.tsx
> +    <div className={chatBoxClassNames} data-test="DesignSystem-AI-Response-Box" {...rest}>
please make this `DesignSystem-AIResponse-Box` as we are using the component name as `AIResponse`, also make the same change if required in other file also.

2024-06-07 09:49 UTC, samyak3009 approved these changes, later dismissed

2024-06-11 09:14 UTC, innosatyam submitted a review, later dismissed

2024-06-11 12:15 UTC, veekays approved these changes

2024-06-11 12:15 UTC, merged