add utilities
innovaccer/design-system pull request #229
Opened 2020-07-17 14:12 UTC by stutirao

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2020-07-29 06:34 UTC, stutirao commented
@satyamyadav i have updated the pr .

2020-08-10 05:22 UTC, satyamyadav requested changes

2020-08-10 05:22 UTC, satyamyadav commented on css/src/components/utilities.css
> +.tg {
@stutirao  Please remove these css classes and use `Grid` classes instead.

2020-08-12 11:43 UTC, aditya-kumawat approved these changes

2020-08-13 07:29 UTC, satyamyadav approved these changes

2020-08-13 07:29 UTC, merged