feat:adds AvatarGroup
innovaccer/design-system pull request #235
Opened 2020-07-20 16:17 UTC by stutirao

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2020-07-20 19:06 UTC, riyalohia requested changes

2020-07-20 19:06 UTC, riyalohia commented on core/components/atoms/avatarGroup/AvatarGroup.tsx
> +        let tooltip = (`${firstName ? firstName : ''}${' '}${lastName ? lastName : ''}`);
Space in a string can be added as: str = '${str1} ${str2}'.

2020-07-20 19:06 UTC, riyalohia commented on core/components/atoms/avatarGroup/AvatarGroup.tsx
> +  });
Loop should run for ind > max only. Also, strNew is not required.

2020-07-20 19:06 UTC, riyalohia commented on css/src/components/avatarGroup.css
> +  border-radius:19px;
Use CSS variables.

2020-07-21 05:28 UTC, aditya-kumawat commented on core/components/atoms/avatarGroup/AvatarGroup.tsx
> +const appearances: Appearance[] = ['primary', 'alert', 'warning', 'success',
No required. Import from Avatar.

2020-07-21 05:30 UTC, aditya-kumawat commented on core/components/atoms/avatarGroup/AvatarGroup.tsx
> +        <div className="OuterBox" >
Not as per BEM convention.

2020-09-03 07:09 UTC, closed without merging