fix(#236): adds ellipsis in GridCell
innovaccer/design-system pull request #238
Opened 2020-07-21 07:33 UTC by aditya-kumawat

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2020-07-22 14:38 UTC, satyamyadav requested changes
@aditya-kumawat  Please check failed build.

2020-07-22 14:50 UTC, aditya-kumawat commented
> @aditya-kumawat Please check failed build.

This PR depends on #237.

2020-07-25 05:24 UTC, satyamyadav requested changes
@aditya-kumawat  This pull request contains commits for other changes, please always create a feature branch from current master only. Please rebase and update this pull request.

2020-07-25 06:19 UTC, satyamyadav submitted a review, later dismissed

2020-07-25 07:16 UTC, satyamyadav approved these changes

2020-07-25 07:16 UTC, merged