fix: adjust chip input max width
innovaccer/design-system pull request #2393
Opened 2024-10-13 01:35 UTC by griseduardo

### What does this implement/fix? Explain your changes.

This PR fix EditableChipInput bug that chip field was going out of the input filled width.

### Does this close any currently open issues?

This PR closes https://github.com/innovaccer/design-system/issues/2061

### Solution

Update maxWidth from `var(--spacing-9)` to `var(--spacing-8)`, by passing maxWidth props in ChipInput

### Difference

## Before

![before-error](https://github.com/user-attachments/assets/ab1bb0a3-dba4-47eb-ad14-f7899cfce72f)

## After

![after-solution](https://github.com/user-attachments/assets/f8dfc739-029c-47b8-9f29-6bd9c65616ce)

### Checklist

Check all those that are applicable and complete.

- [x] Merged with latest `master` branch

2024-10-14 08:37 UTC, anuradha9712 requested changes
Please submit a pull request with `develop` as the target branch.

2024-10-14 08:39 UTC, anuradha9712 commented
please create a separate PR for editableChipInput and README file changes.

2024-10-14 08:55 UTC, anuradha9712 commented on core/components/molecules/chipInput/ChipInput.tsx
> +        maxWidth="var(--spacing-8)"
There is no need to pass `maxWidth` prop to Chip as it is already accommodated in the `{...rest}` through `chipOptions` prop

2024-10-14 09:14 UTC, anuradha9712 commented
@griseduardo Thank you for your contribution. Another approach to solve this issue could be to simply pass `maxWidth`  to the `chipInputOptions` prop like the following in the stories file only ([refer to this](https://github.com/innovaccer/design-system/blob/master/core/components/molecules/editableChipInput/__stories__/index.story.jsx))

```
<EditableChipInput 
  chipInputOptions={{
   chipOptions: {{maxWidth: "var(--spacing-8)"}}
  }}
/>
```
Initial maxWidth `var(--spacing-9)` is set to accommodate large number of use-cases. Also there is option available to update the maxWidth based on various use-cases just like in this EditableChipInput case.

Please let me know if this approach works for you or in case you need any more discussion.

2024-10-14 10:05 UTC, anuradha9712 commented
Please update the commit message to `fix(editableChipInput): fix overflow behavior of editableChipInput component` or something similar to this

2024-10-14 13:02 UTC, griseduardo commented
@anuradha9712 Thank you for the suggestions, I applied them here

2024-10-17 05:46 UTC, anuradha9712 approved these changes

2024-10-17 05:46 UTC, merged