chore: adds custom scrollbar in table
innovaccer/design-system pull request #240
Opened 2020-07-21 10:06 UTC by riyalohia

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2020-07-22 14:47 UTC, satyamyadav requested changes
@riyalohia  Please rebase your branch with current master branch.

2020-07-22 14:59 UTC, aditya-kumawat commented on css/src/components/grid.css
> +    width: var(--spacing);
Update size to --spacing-l.

2020-07-22 14:59 UTC, aditya-kumawat commented on css/src/components/grid.css
> +    border-radius: var(--spacing-m);
Update size to --spacing

2020-07-24 10:03 UTC, aditya-kumawat commented
@riyalohia Please update PR/commit name as per convention.

2020-07-27 06:06 UTC, satyamyadav approved these changes

2020-07-27 06:07 UTC, merged