feat: adds unit testing
innovaccer/design-system pull request #284
Opened 2020-08-18 06:38 UTC by stutirao

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2020-08-19 07:34 UTC, riyalohia requested changes

2020-08-19 07:34 UTC, riyalohia commented on core/components/atoms/badge/__tests__/Badge.test.tsx
> +
Add a test for `span` element.

2020-08-19 07:34 UTC, riyalohia commented on core/components/atoms/pills/__tests__/Pills.test.tsx
> +    expect(getByTestId('DesignSystem-Pills')).toHaveClass('Pills');
Remove this test and add a test for `span` element in a different describe block.

2020-08-19 07:34 UTC, riyalohia commented on core/components/atoms/progressBar/__tests__/ProgressBar.test.tsx
> +  it('renders classes', () => {
Remove this test.

2020-08-19 07:34 UTC, riyalohia commented on core/components/atoms/progressBar/__tests__/ProgressBar.test.tsx
> +    expect(getByTestId('DesignSystem-ProgressBar')).toHaveStyle({ width: '50%' });
Add test for value < 0 and value > max

2020-08-19 07:34 UTC, riyalohia commented on core/components/atoms/progressRing/__tests__/ProgressRing.test.tsx
> +    expect(getByTestId('DesignSystem-ProgressRing')).toHaveAttribute('viewBox', '0 0 50 50');
Remove viewBox test.

2020-08-19 07:34 UTC, riyalohia commented on core/components/atoms/progressRing/__tests__/ProgressRing.test.tsx
> +    expect(getByTestId('DesignSystem-ProgressRing--Circle')).toHaveClass('Ring-indicator');
Remove `Ring-indicator` class test

2020-08-19 07:34 UTC, riyalohia commented on core/components/atoms/progressRing/__tests__/ProgressRing.test.tsx
> +    expect(getByTestId('DesignSystem-ProgressRing--Circle')).toHaveAttribute('fill', 'none');
Remove `fill` test.

2020-08-19 07:34 UTC, riyalohia commented on core/components/atoms/statusHint/__tests__/StatusHint.test.tsx
> +    expect(getByTestId('DesignSystem-StatusHint')).toHaveClass('StatusHint');
Remove this test.

2020-08-19 07:34 UTC, riyalohia commented on core/components/atoms/statusHint/__tests__/StatusHint.test.tsx
> +    expect(getByTestId('DesignSystem-StatusHint--Icon')).toHaveClass('StatusHint-icon');
Remove this test and add test for `span` element.

2020-08-19 15:06 UTC, riyalohia requested changes

2020-08-19 15:06 UTC, riyalohia commented on core/components/atoms/paragraph/__tests__/Paragraph.test.tsx
> +  it('renders children', () => {
Add a test for `p` tag.

2020-08-19 15:06 UTC, riyalohia commented on core/components/atoms/subheading/__tests__/Subheading.test.tsx
> +    expect(getByTestId('DesignSystem-Subheading')).toHaveTextContent('Subheading');
Add test for `h4` tag.

2020-08-19 15:08 UTC, riyalohia commented
@stutirao Add `class override` test for each component.

2020-08-20 23:50 UTC, riyalohia approved these changes

2020-08-21 07:09 UTC, satyamyadav approved these changes

2020-08-21 07:09 UTC, merged