feat(file uploader):made the icon a transparent icon button
innovaccer/design-system pull request #680
Opened 2021-05-17 16:42 UTC by adityajhajharia

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2021-05-18 07:13 UTC, satyamyadav commented on core/components/molecules/fileUploader/FileUploaderStatus.tsx
> +import Button from '@/components/atoms/button/Button';
Please update import statement to `import { Button } from '@/index'`;

2021-05-18 07:14 UTC, satyamyadav commented on core/components/molecules/fileUploader/FileUploaderStatus.tsx
>            name="refresh"
Please remove `name` prop.

2021-05-18 07:14 UTC, satyamyadav commented on core/components/molecules/fileUploader/FileUploaderStatus.tsx
>            className="mr-4 cursor-pointer"
Please remove `cursor-pointer` class.

2021-05-18 07:15 UTC, satyamyadav commented on core/components/molecules/fileUploader/FileUploaderItem.tsx
> +            className="py-2 px-2 my-3 mx-3 cursor-pointer "
Please remove `cursor-pointer` class. Also avoid using padding classes on button.

2021-05-19 10:44 UTC, riyalohia approved these changes, later dismissed

2021-05-20 08:52 UTC, satyamyadav requested changes
Please update title and commit of the pull request to `feat(FileUploaderItem): Replaces Icon component with transparent icon Button component.
`

2021-05-21 07:10 UTC, satyamyadav approved these changes

2021-05-21 07:11 UTC, merged