feat(Tab): improves API for custom tab
innovaccer/design-system pull request #804
Opened 2021-08-02 06:20 UTC by riyalohia

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2021-08-04 07:00 UTC, innosatyam requested changes

2021-08-05 04:12 UTC, satyamyadav requested changes

2021-08-05 04:12 UTC, satyamyadav commented on core/components/molecules/tabs/__tests__/Tabs.test.tsx
Add tests for Tab as children of Tabs and content in Tab, inline content and tabs without activeIndex in props.

2021-08-06 06:02 UTC, satyamyadav approved these changes

2021-08-06 06:04 UTC, innosatyam approved these changes

2021-08-06 06:04 UTC, merged