docs: prevent shifting icon in Collapsible
innovaccer/design-system pull request #919
Opened 2021-10-16 21:02 UTC by AlithAnar

### What does this implement/fix? Explain your changes.

This fix adds "Text--regular" class to the icon className to align the appearing text line height. Before the fix a text that appears after expanding the panel increased the height of the header row and moved the icon a little bit.
...

### Does this close any currently open issues?
fixes #917
...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2021-10-17 10:39 UTC, satyamyadav requested changes

2021-10-17 10:39 UTC, satyamyadav commented on core/components/atoms/collapsible/__stories__/index.story.tsx
> +        <div className="d-flex pt-4" style={{ height: '20px' }}>
@AlithAnar Please avoid using style attribute, we follow BEM based css classnames and avoid inline styling. The issue seems to be due to line height mismatch for text and icon, you can add a helper class or text related class to provide the same line height as of tex to the icon (example `Text--regular`).

2021-10-17 10:39 UTC, satyamyadav commented on core/components/atoms/collapsible/__stories__/index.story.tsx
> +        <div className="d-flex pt-4" style={{ height: "20px"}}>
@AlithAnar Please avoid inline styling.

2021-10-17 11:16 UTC, AlithAnar commented on core/components/atoms/collapsible/__stories__/index.story.tsx
> +        <div className="d-flex pt-4" style={{ height: '20px' }}>
fixed in https://github.com/innovaccer/design-system/pull/919/commits/d23dcd332bed16a10c85c565d2b697962003b9b7

2021-10-17 11:16 UTC, AlithAnar commented on core/components/atoms/collapsible/__stories__/index.story.tsx
> +        <div className="d-flex pt-4" style={{ height: "20px"}}>
fixed in https://github.com/innovaccer/design-system/pull/919/commits/d23dcd332bed16a10c85c565d2b697962003b9b7

2021-10-17 15:05 UTC, satyamyadav approved these changes

2021-10-17 15:09 UTC, satyamyadav requested changes
@AlithAnar  Can you please squash the commits into one commit.

2021-10-17 16:15 UTC, AlithAnar commented
> @AlithAnar Can you please squash the commits into one commit.

done

2021-10-18 19:26 UTC, satyamyadav approved these changes

2021-10-18 19:26 UTC, merged