fix(button.css): fix transparent button active state
innovaccer/design-system pull request #928
Opened 2021-10-17 13:23 UTC by indremak

fix #925

### What does this implement/fix? Explain your changes.
Fixes active state in button component's transparent variant
...

### Does this close any currently open issues?
Fix #925 
...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2021-10-17 15:28 UTC, satyamyadav requested changes
Two points regarding the pull request you need to update are: 
- Create the pull request on develop branch.
- There should not be any merge commit and there should be only one commit, to avoid merge commits on taking pull from upstream us `--rebase` flag , like `git pull --rebase upstream develop`.

2021-10-17 15:28 UTC, satyamyadav commented on css/src/components/button.css
> +.Button--transparent:focus:active {
@indremak Please add a new selector combination instead of updating the existing as we need to make it like 
`:focus`  `:active`  `:focus:active` in sequence, first one will add the styling for focus and later two will have same properties and work as active.

2021-10-18 15:21 UTC, indremak commented on css/src/components/button.css
> +.Button--transparent:focus:active {
Thanks for reviewing! I am not sure if I understood you correctly. Do you want me to add two selectors for `active` state? 
As in this example: 
```
.Button--transparent:focus {
    background: color-mod(var(--stone-light) a(0.2));
    /* box-shadow: var(--shadow-spread) var(--secondary-shadow); */
}

.Button--transparent:active { //this will never be applied because next selector has higher specificity
	background: var(--secondary);
}

.Button--transparent:focus:active {
	background: var(--secondary);
}
```
When button is active, it is focused as well, and because this selector has higher specificity than selector with only `:focus` pseudo class this style is applied, so I am not sure if any changes are needed. 
Could you please elaborate what changes are you expecting?

2021-10-18 19:09 UTC, satyamyadav commented on css/src/components/button.css
> +.Button--transparent:focus:active {
@indremak You got it right, `:focus:active` will be applied for and `:active` will not be, but I just want to have active if it can be toggled without the focus state like we do from developer tools. Also I think first element enters in active then focus state.

2021-10-18 19:15 UTC, satyamyadav commented on css/src/components/button.css
> +.Button--transparent:focus:active {
In addition this may also introduce some browser specific inconsistency. Some may be listed here https://zellwk.com/blog/inconsistent-button-behavior/

2021-10-20 05:49 UTC, satyamyadav approved these changes

2021-10-21 05:34 UTC, merged